### PR TITLE
Update filter height to not make it too small

### PR DESCRIPTION
**Pull request by SuperNerdEric**
Closes https://github.com/weirdgloop/osrs-dps-calc/issues/71

| Entries| Height | 
| ------ |:-------:|
| 1        | 35px |
| 2        | 70px |
| 3        | 105px |
| 4        | 140px |
| 5        | 175px |
| 6+        | 200px |

image

### CODE REVIEW

**Review by jayktaylor — CHANGES_REQUESTED** [review]
This seems to work fine for the equipment combobox, but still exhibits issues with the monster one (probably because the item heights are different).

Maybe there's something smarter we can do here, or perhaps we can pass a value to the generic `Combobox` component so that we can set the `height` on the `List` separately for both the equipment combobox and the monster combobox? I'm less of a fan of that option, but if it's the best way forward, then I'm not opposed.

Screenshot 2024-01-12 at 22 47 19

**Comment by SuperNerdEric** [comment]
> This seems to work fine for the equipment combobox, but still exhibits issues with the monster one (probably because the item heights are different).
> 
> Maybe there's something smarter we can do here, or perhaps we can pass a value to the generic `Combobox` component so that we can set the `height` on the `List` separately for both the equipment combobox and the monster combobox? I'm less of a fan of that option, but if it's the best way forward, then I'm not opposed.
>

So I was working on this some and part of the problem I'm running into is that:

- items/spells rows always have the same size
   -  20 + 15 = 35px
- monster rows have variable sizes
   - 14 + 15 = 29px
   - 16 + 15 = 31px
   - 28 + 15 = 43px (long name wrapped)

The simplest solution would probably be to assume items/spells are 35px and monsters are 29px. There may still be a few cases in monsters where you get a scrollbar unnecessarily or a little extra blank space, but I think this is already occurring for monsters.

Alternatively you would have to calculate the total row heights for all the filtered items and do some check like this.
`height={(getTotalFilteredHeight() < 200 ? getTotalFilteredHeight() : 200)}`

But I don't think all of the row heights are even available due to the virtualization.

**Comment by jayktaylor** [comment]
Do you think that there's a solution to be found where we can make all of the monster rows the same size regardless of the long name wrapping or not? Maybe by setting a min/max height? I don't know if it's likely to make the rows for the monsters with short names look a bit silly/chunky, but could be worth a shot compared to trying to cater for three different potential heights?

**Comment by SuperNerdEric** [comment]
> Do you think that there's a solution to be found where we can make all of the monster rows the same size regardless of the long name wrapping or not? Maybe by setting a min/max height? I don't know if it's likely to make the rows for the monsters with short names look a bit silly/chunky, but could be worth a shot compared to trying to cater for three different potential heights?

Honestly if you just treat all monsters as if the row height is 35px it's not **that** bad. The shorter ones get some extra spacing around it, but the wrapped ones are a little tight (though they don't seem vertically centered)

image

**Comment by jayktaylor** [comment]
Perhaps it's worth considering switching using `react-window` to [react-virtuoso](https://github.com/petyosi/react-virtuoso) instead, which claims to handle automatically detecting each item's height with no configuration. Personally, I'm not really bothered which virtualisation library we use as long as it is performant. If nobody gets to it first, I may look into this at the weekend.

**Comment by Nightfirecat** [comment]
I'm far from an expert in React components, but style-wise, this seems like a case where some fixed max-height would solve the problem much more effectively than an explicit height based on the number of items given. If a component offers that as a solution, that should be all that's needed for this to work correctly.

**Pull request closed without merging**
