### PR TITLE
added tome of earth and dragon hunter working with slayer helm

### PR DESCRIPTION
**Pull request by Aerosplice**
added tome of earth with the tome of water and tome of fire 10% dps calc

### CODE REVIEW

**Comment by Aerosplice** [comment]
Also added dragon hunter wand to not be exclusive with slayer helm/salve stuff

**Comment by Aerosplice** [comment]
I wasn't exactly sure how to go about doing all this sorry

**Comment by LlemonDuck** [comment]
tome of earth merged via #502 
dhw changes via #503

**Comment by LlemonDuck** [comment]
Thanks for the PR!

**Pull request closed without merging**
