### PR TITLE
added more equipment aliases

### PR DESCRIPTION
**Pull request by crab-pancake**
collapsed imbued god capes and imbued max god capes, collected all charged/blessed/max dizana's quiver variants.  added deadman kitted weapons. 
put araxyte slayer helms into slayer helms. 
added poh heraldic gear to respective items.
added new alias for ironman helm/platebody/platelegs, vambraces not done. 
removed fully broken (0) equipment from barrows aliases

still need to complete aliases for gilded -> rune equipment

### CODE REVIEW

**Comment by rnorton5432** [comment]
This is generated by `scripts/generateEquipmentAliases.py`, so you'll need to edit that script to pick up these changes automatically from the wiki instead of editing it by hand.

**Comment by LlemonDuck** [comment]
This file is generated from `scripts/generateEquipmentAliases.py`, so you'll need to edit that instead of editing the aliases file directly.

**Comment by crab-pancake** [comment]
Thought the file looked a bit weird, ty will do.

**Comment by LlemonDuck** [comment]
closing for now. feel free to reopen if you make changes to the python script

**Pull request closed without merging**
