### PR TITLE
Add more equipment aliases

### PR DESCRIPTION
**Pull request by lezed1**
Add support for grouping more ornament kits. Everything listed on https://oldschool.runescape.wiki/w/Ornament_kit should be supported!

This PR also moved the generated equipment aliases to a separate file to make it easier to regenerate the file. I also updated the workflow to regenerate the generated equipment aliases when generating other files.

This should handle most if not everything remaining in #39!

### CODE REVIEW

**Comment by crab-pancake** [comment]
this is very cool. any chance mystic variants (light/dark/enchanted/darkness) could be added as well?

**Review by jayktaylor — CHANGES_REQUESTED** [review]
Very nice work!

Note however that the Python script was never intended to be used to fully generate the equipment aliases file (the comment at the top of it says that too 😛), because it's likely there's some aliases that we'll end up adding non-programmatically.

For example, your updated constant for aliases misses out some of the variants we manually added, such as crystal armour variants in https://github.com/weirdgloop/osrs-dps-calc/commit/685e97ec6e0e06ccc830e85d9e1c5f47173dfc0b

If we can re-add the ones that are missing back in programmatically in the Python script (probably another regex match), then I'm happy to approve this.

**Comment by SuperNerdEric** [comment]
I guess it worries me a little bit to have a bunch of different regex in Python automatically running in the CI workflow without someone manually looking at it to check what changed. 

Regex is something that is easy to get slightly wrong and get unintended matches or subtle mistakes.

**Comment by jayktaylor** [comment]
I think I agree. Happy to keep maintaining a script for scraping the equipmentAliases if we ever need to, but I wouldn't want it to update automatically as part of the CI process because I can easily see us manually adding more variants.

**Comment by lezed1** [comment]
I'm happy to remove the automatic running if you want. I think this is set up similarly to wikisync where it runs automatically but stops after creating a PR, so I was happy with it since a person must review it before anything gets pushed. If that doesn't sit right with you, I will happily remove it!

**Comment by lezed1** [comment]
@crab-pancake The other Mystic versions are added!

**Review by jayktaylor — APPROVED** [review]

**Pull request merged**
