### PR TITLE
adding monster attribute req to some sections

### PR DESCRIPTION
**Pull request by crab-pancake**
and moving crystal dmg buff before salve

### CODE REVIEW

**Comment by pnorton5432** [comment]
Do you have something backing up that crystal bonus happens before salve?

**Comment by LlemonDuck** [comment]
Do you have something backing up that crystal bonus happens before salve?

**Comment by LlemonDuck** [comment]
also conflicts with the just-merged #42

**Comment by LlemonDuck** [comment]
i've rebased this, but let me know about the salve / crystal interaction comment above, and whether it should also apply to the attackRoll section

**Comment by crab-pancake** [comment]
crystal -> salve/slayer helm order for max hit can be tested fairly easily

i would assume its the same order for accuracy but much more difficult to test

**Review by LlemonDuck — APPROVED** [review]

**Pull request merged**
